djangoProject1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='mainapp/')),
    path('mainapp/', include('mainapp.urls', namespace='mainapp')),

]

mainapp/urls.py
from mainapp import views
from django.urls import path
from mainapp.apps import MainappConfig

app_name = MainappConfig.name

urlpatterns = [
    path('contacts/', views.ContactsView.as_view(), name='contacts'),
    path('courses/', views.CoursesListView.as_view(), name='courses'),
    path('docsite/', views.DocSiteView.as_view(), name='docsite'),
    path('', views.IndexView.as_view(), name='index'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('news/', views.NewsView.as_view(), name='news'),
]

mainapp/models.py
from django.db import models

# Create your models here.

mainapp/views.py
from django.http import HttpResponse
from django.views.generic import TemplateView
from datetime import datetime


# class HelloWorldView(View):
#
#     def get(self, request, *args, **kwargs):
#         return HttpResponse("Hello world!")
#
# # def hello_world(request):
# #     return HttpResponse("Hello world!")
#
# def blog(request, **kwargs):
#     return HttpResponse(f'{kwargs}')

class ContactsView(TemplateView):
    template_name = 'mainapp/contacts.html'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['contacts'] = [
            {
                'map': 'https://yandex.ru/map-widget/v1/-/CCUAZHcrhA',
                'city': 'Санкт‑Петербург',
                'phone': '+7-999-11-11111',
                'email': 'geeklab@spb.ru',
                'address': 'территория Петропавловская крепость, 3Ж',
            },
            {
                'map': 'https://yandex.ru/map-widget/v1/-/CCUAZHX3xB',
                'city': 'Казань',
                'phone': '+7-999-22-22222',
                'email': 'geeklab@kz.ru',
                'address': 'территория Кремль, 11, Казань, Республика Татарстан, Россия',
            },
            {
                'map': 'https://yandex.ru/map-widget/v1/-/CCUAZHh9kD',
                'city': 'Москва',
                'phone': '+7-999-33-33333',
                'email': 'geeklab@msk.ru',
                'address': 'Красная площадь, 7, Москва, Россия',
            },
        ]
        return context_data

class CoursesListView(TemplateView):
    template_name = 'mainapp/courses_list.html'

class DocSiteView(TemplateView):
    template_name = 'mainapp/doc_site.html'

class IndexView(TemplateView):
    template_name = 'mainapp/index.html'

class LoginView(TemplateView):
    template_name = 'mainapp/login.html'

class NewsView(TemplateView):
    template_name = 'mainapp/news.html'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        # context_data['title'] = 'Новость раз'
        # context_data['preview'] = 'Превью к новости раз'
        # context_data['date'] = '2022-01-01'
        context_data['object_list'] = [
            {
                'title': 'Новость раз',
                'preview': 'Превью к новости раз',
                'date': datetime.now()
            },
            {
                'title': 'Новость два',
                'preview': 'Превью к новости два',
                'date': datetime.now()
            },
            {
                'title': 'Новость три',
                'preview': 'Превью к новости три',
                'date': datetime.now()
            },
            {
                'title': 'Новость четыре',
                'preview': 'Превью к новости четыре',
                'date': datetime.now()
            },
            {
                'title': 'Новость пять',
                'preview': 'Превью к новости пять',
                'date': datetime.now()
            },
            {
                'title': 'Новость шесть',
                'preview': 'Превью к новости шесть',
                'date': datetime.now()
            },

        ]


        return context_data

mainapp/templates/mainapp/base.html
{% load static %}

<!doctype html>
<html lang="ru">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static '/css/bootstrap.min.css' %}">

    <!-- ChartJS -->
    <link rel="stylesheet" href="{% static '/css/Chart.min.css' %}">

    <!-- FontAwesome -->
    <link rel="stylesheet" href="{% static '/css/fontawesome.all.min.css' %}">

    <title>Welcome to Braniac!</title>
</head>

<body>



    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <a class="navbar-brand" href="{% url 'mainapp:index' %}">
                <img src="{% static '/img/logo.png' %}" alt="">
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            {%  include 'mainapp/includes/inc_main_menu.html' %}

        </div>
    </nav>





    <div class="container-md">

        {% block content %}
        {% endblock %}

    </div>

    <!-- Footer -->

    <div class="container-lg mt-auto">
        <hr>
        <div class="row justify-content-center">
            <div class="col-sm-6 col-md-3 text-center">
                <p>
                    <strong>Braniac</strong>
                </p>
                <p>
                <ul class="list-unstyled">
                    <li><a href="index.html">Домашняя</a></li>
                    <li><a href="news.html">Новости</a></li>
                    <li><a href="login.html">Войти</a></li>
                </ul>
                </p>
            </div>
            <div class="col-sm-6 col-md-3 text-center">
                <p>
                    <strong>Полезное</strong>
                </p>
                <p>
                <ul class="list-unstyled">
                    <li><a href="#">Положения &amp; Условия</a></li>
                    <li><a href="#">Конфиденциальность &amp; Cookies</a></li>
                    <li><a href="#">Документация по API</a></li>
                    <li><a href="doc_site.html">Документация по сайту</a></li>
                </ul>
                </p>
            </div>
            <div class="col-sm-6 col-md-3 text-center">
                <p>
                    <strong>Мы в социальных сетях</strong>
                </p>
                <p>
                <div class="row justify-content-around">
                    <div><a href="#"><i class="fab fa-vk fa-2x"></i></a></div>
                    <div><a href="#"><i class="fab fa-facebook-f fa-2x"></i></a></div>
                    <div><a href="#"><i class="fab fa-instagram fa-2x"></i></a></div>
                    <div><a href="#"><i class="fab fa-pinterest-p fa-2x"></i></a></div>
                </div>
                </p>
                <p>
                    <strong>Наше приложение</strong>
                </p>
                <p>
                <div class="row justify-content-around">
                    <div><a href="#"><i class="fab fa-app-store fa-2x"></i></a></div>
                    <div><a href="#"><i class="fab fa-google-play fa-2x"></i></a></div>
                    <div><a href="#"><i class="fab fa-windows fa-2x"></i></a></div>
                </div>
                </p>
            </div>
        </div>
        <div class="row justify-content-center">
            <div>
                <p><small>&copy; GeekBrains 2022</small></p>
            </div>
        </div>
    </div>

    <!-- /Footer -->




    <!-- JavaScript section -->
    <!-- Bootstrap -->
    <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <!-- ChartJs -->
    <script src="{% static 'js/Chart.min.js' %}"></script>

    <!-- FontAwesome -->
    <script src="{% static 'js/fontawesome.all.min.js' %}"></script>



</body>

</html>

mainapp/templates/mainapp/contacts.html
{% extends 'mainapp/base.html' %}
{% load email_to_link %}
{% block content %}

<p>
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">Наши контакты</h1>
    <p class="lead">Обязательно свяжитесь с нами! Ваш комфорт - наша забота.</p>
  </div>
</div>
</p>
<p>
<div class="row justify-content-around mt-n2">

{% for contact in contacts %}
  
  <div class="col-sm-6 col-md-6 col-lg-4 pb-2">
    <div class="card h-100 shadow">
      <div class="card-body">
        <div style="position:relative;overflow:hidden;">
            <iframe  src="{{ contact.map }}" width="100%" height="300"
                     frameborder="0" allowfullscreen="true" style="position:relative; border-radius: 4px;"></iframe>
        </div>
        <h5 class="card-title">{{ contact.city }}</h5>
        <p class="card-text">
        <ul class="list-unstyled">
          <li>Телефон</li>
          <li><strong>{{ contact.phone }}</strong></li>
        </ul>
        <ul class="list-unstyled">
          <li>Email</li>
          <li><strong>{{ contact.email|email_to_link }}</strong></li>
        </ul>
        <ul class="list-unstyled">
          <li>Адрес</li>
          <li><strong>{{ contact.address }}</strong></li>
        </ul>
        </p>
      </div>
    </div>
  </div>
  
{% endfor %}
  
</div>
</p>

{% endblock %}

mainapp/templates/mainapp/courses_list.html
{% extends 'mainapp/base.html' %}

{% block content %}

        
    <div class="row justify-content-center mt-3">
        

                <div class="card col-sm-12 col-md-6 col-lg-4 border-0">
                <a href="#">
                    <img src="/static/img/course001.jpg" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title text-center">Web Python</h5>
                    </div>
                </a>
                </div>

        

                <div class="card col-sm-12 col-md-6 col-lg-4 border-0">
                <a href="#">
                    <img src="/static/img/course002.jpg" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title text-center">Web Golang</h5>
                    </div>
                </a>
                </div>

        

                <div class="card col-sm-12 col-md-6 col-lg-4 border-0">
                <a href="#">
                    <img src="/static/img/course003.jpg" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title text-center">Web JavaScript</h5>
                    </div>
                </a>
                </div>

        

                <div class="card col-sm-12 col-md-6 col-lg-4 border-0">
                <a href="#">
                    <img src="/static/img/course004.jpg" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title text-center">Web Java</h5>
                    </div>
                </a>
                </div>

        

                <div class="card col-sm-12 col-md-6 col-lg-4 border-0">
                <a href="#">
                    <img src="/static/img/course005.jpg" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title text-center">Web PHP</h5>
                    </div>
                </a>
                </div>

        

                <div class="card col-sm-12 col-md-6 col-lg-4 border-0">
                <a href="#">
                    <img src="/static/img/course006.jpg" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title text-center">Python AI</h5>
                    </div>
                </a>
                </div>

        

                <div class="card col-sm-12 col-md-6 col-lg-4 border-0">
                <a href="#">
                    <img src="/static/img/course007.jpg" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title text-center">DevOps</h5>
                    </div>
                </a>
                </div>

        
    </div>
    <div class="row justify-content-center align-items-center mt-3 mb-n3">
  <nav aria-label="Page navigation example">
    <ul class="pagination">
      <li class="page-item"><a class="page-link" href="#">Previous</a></li>
      <li class="page-item"><a class="page-link" href="#">1</a></li>
      <li class="page-item"><a class="page-link" href="#">2</a></li>
      <li class="page-item"><a class="page-link" href="#">3</a></li>
      <li class="page-item"><a class="page-link" href="#">Next</a></li>
    </ul>
  </nav>
</div>


{% endblock %}

mainapp/templates/mainapp/doc_site.html
{% extends 'mainapp/base.html' %}

{% block content %}

        
<div class="row justify-content-center align-items-center mt-3">
  <div class="col-md-9">
    <div class="card">
      <div class="card-header">
        Документация по сайту
      </div>
      <div class="card-body">

        <h5 class="card-title">CSS-стили</h5>
        <p class="card-text">
        <ul>
          <li><a href="https://getbootstrap.com/docs/4.6/getting-started/introduction/" target="_blank">Bootstrap
              v4.6</a></li>
          <li><a href="https://bootswatch.com/lumen/" target="_blank">Bootstrap theme: Lumen</a></li>
        </ul>
        </p>

        <h5 class="card-title">Иконки</h5>
        <p class="card-text">
          <a href="https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use">FontAwesome 5.15.3</a>
        </p>

        <h5 class="card-title">Графики</h5>
        <p class="card-text">
          <a href="https://www.chartjs.org/">ChartJS</a>
        </p>

        <h5 class="card-title">Графика</h5>
        <p class="card-text">
        <ul>
          <li><a href="https://www5.flamingtext.com/" target="_blank" rel="noopener noreferrer">Логотип by
              flamingtext.com</a></li>
          <li><a href="https://www.pexels.com/ru-ru" target="_blank" rel="noopener noreferrer">Фотографии by
              pexels.com</a>. Все изображения распространяются под бесплатной лицензией. Для страницы обзоров фотографии
            должны быть с соотношением сторон кратным 2.912 (например, 1920x659)</li>
          <li><a href="https://getavataaars.com/" target="_blank" rel="noopener noreferrer">Аватарки пользователей by
              getavataaars.com</a></li>
        </ul>
        </p>

      </div>
    </div>
  </div>
</div>


{% endblock %}

mainapp/templates/mainapp/includes/inc_main_menu.html
<div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item ">
            <a class="nav-link" href="{% url 'mainapp:news' %}">Новости</a>
        </li>
        <li class="nav-item ">
            <a class="nav-link" href="{% url 'mainapp:courses' %}">Курсы</a>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="ddProfile" role="button" data-toggle="dropdown"
               aria-haspopup="true" aria-expanded="false">
                Профиль
            </a>
            <div class="dropdown-menu" aria-labelledby="ddProfile">
                <a class="dropdown-item" href="#">Редактировать профиль</a>
                <a class="dropdown-item" href="#">Мои курсы</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Модерация</a>
                <a class="dropdown-item" href="#">Административный раздел</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Выход</a>
            </div>
        </li>
        <li class="nav-item ">
            <a class="nav-link" href="{% url 'mainapp:contacts' %}">Контакты</a>
        </li>
    </ul>
    <span><a href="#">🇷🇺</a> <i class="fas fa-grip-lines-vertical"></i> <a href="#">🇬🇧</a></span>
</div>

mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}

{% block content %}

    <div id="carouselExampleIndicators" class="carousel slide carousel-fade" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner" style="background-color: #777; font-size: 1.25rem;">
            <div class="carousel-item active">
                <img src="/static/img/slider001.jpg" class="d-block w-100" alt="" style="opacity: 0.3;">
                <div class="carousel-caption d-none d-md-block">
                    <h3>Будь продуктивным</h3>
                    <p>Изучай только актуальные тренды современного IT</p>
                </div>
            </div>
            <div class="carousel-item">
                <img src="/static/img/slider002.jpg" class="d-block w-100" alt="" style="opacity: 0.3;">
                <div class="carousel-caption d-none d-md-block">
                    <h3>Учись где угодно</h3>
                    <p>Парк, библиотека или дома под тёплым пледом - выбирай время и место учёбы сам</p>
                </div>
            </div>
            <div class="carousel-item">
                <img src="/static/img/slider003.jpg" class="d-block w-100" alt="" style="opacity: 0.3;">
                <div class="carousel-caption d-none d-md-block">
                    <h3>Braniac - это МЫ</h3>
                    <p>Вливайся в нашу IT-тусовку - нас уже более 5000 брайниаков</p>
                </div>
            </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>

    <div class="jumbotron">
        <h1 class="display-4">Приветствую, путник!</h1>
        <p class="lead">
            На данном портале мы собрали сообщество людей объединённых одной целью - получать знания! В современном мире
            уже сложно представить человека не общающегося с компьютером. Повсеместное проникновение интернета дало
            возможность объеденить людей и сделать знания доступными как никогда ранее. У тебя есть уникальная
            возможность получить актуальные знания используя современные технологии. Не упусти свой шанс и переходи на
            вкладку "Курсы", записывайся на курсы и становись востребованным специалистом.
        </p>
    </div>

    <h3>Отзывы участников сообщества</h3>


    <div class="row text-center">

        
            <div class="col-lg-4">
                <img src="/static/img/user001.png" alt="" style="max-width: 140px;">
                <h2>Лера</h2>
                <p>Выучила Python и получаю 300кк в секунду! Спасибо Браниаку!</p>
            </div>
        
            <div class="col-lg-4">
                <img src="/static/img/user002.png" alt="" style="max-width: 140px;">
                <h2>Антоша</h2>
                <p>Больше не туплю в excel - только БД только хардкор!</p>
            </div>
        
            <div class="col-lg-4">
                <img src="/static/img/user003.png" alt="" style="max-width: 140px;">
                <h2>Леонард</h2>
                <p>Как пропатчить KDE под FreeBSD?!</p>
            </div>
        

    </div>

    <div class="my-5">
        <hr>
    </div>

    <div class="row justify-content-center align-items-center">
        <div class="col-md-7">
            <h1>Сотни готовых курсов от лучших авторов</h1>
            <p>Выбирай из огромной коллекции готовых решений для самообразования</p>
        </div>
        <div class="col-md-5">
            <img src="/static/img/promo001.jpg" alt="" class="w-100 h-100 rounded" style="opacity: 0.7;">
        </div>
    </div>

    <div class="my-5">
        <hr>
    </div>

    <div class="row justify-content-center align-items-center">
        <div class="col-md-5">
            <img src="/static/img/promo002.jpg" alt="" class="w-100 h-100 rounded" style="opacity: 0.7;">
        </div>
        <div class="col-md-7">
            <h1>Монетизируй знания</h1>
            <p>Эксперт в свой области - давай к нам! Выгодные условия для тебя и пользователи со всего мира на нашей
                платформы</p>
        </div>
    </div>

    <div class="my-5">
        <hr>
    </div>

    <div class="row justify-content-center align-items-center">
        <div class="col-md-7">
            <h1>Вместе мы сила</h1>
            <p>Проекты любой сложности становятся легче, если ты в компании единомышленников. Присоединяйся!</p>
        </div>
        <div class="col-md-5">
            <img src="/static/img/promo003.jpg" alt="" class="w-100 h-100 rounded" style="opacity: 0.7;">
        </div>
    </div>

{% endblock %}

mainapp/templates/mainapp/login.html
<!doctype html>
<html lang="ru">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">

    <!-- ChartJS -->
    <link rel="stylesheet" href="/static/css/Chart.min.css">

    <!-- FontAwesome -->
    <link rel="stylesheet" href="/static/css/fontawesome.all.min.css">

    <title>Welcome to GeekLab!</title>
</head>

<body>





<div class="row justify-content-around align-items-center" style="height: 100vh; margin: 0px">
  <div class="text-center">
    <p>
      <a href="/"><img src="/static/img/logo.png" alt=""></a>
    </p>
    <h2>Вход пользователя</h2>
    <form>
      <p>
        <input id="id_username" class="form-control" type="text" name="username" placeholder="Имя пользователя"
          required="" autofocus="">
      </p>
      <p>
        <input id="id_password" class="form-control" type="password" name="password" placeholder="Пароль" required="">
      </p>
      <p>
        <button type="submit" class="btn btn-primary btn-block">Войти</button>
      </p>
    </form>
    <p class="text-right">
      <a href=""><small>Забыли пароль?</small></a>
    </p>
    <h4>Вход через социальные сети</h4>
    <p>
    <div class="btn-group btn-block" role="group">
      <a class="btn btn-primary" href="#" role="button"><i class="fab fa-vk"></i></a>
      <a class="btn btn-primary" href="#" role="button"><i class="fab fa-github"></i></a>
      <a class="btn btn-primary" href="#" role="button"><i class="fab fa-facebook"></i></a>
    </div>
    </p>
  </div>
</div>








    <!-- JavaScript section -->
    <!-- Bootstrap -->
    <script src="/static/js/jquery-3.6.0.min.js"></script>
    <script src="/static/js/popper.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>

    <!-- ChartJs -->
    <script src="/static/js/Chart.min.js"></script>

    <!-- FontAwesome -->
    <script src="/static/js/fontawesome.all.min.js"></script>



</body>

</html>

mainapp/templates/mainapp/news.html
{% extends 'mainapp/base.html' %}

{% block content %}

        

<div class="row">

  <div class="col-lg-8">
    {% for new_item in object_list %}
    <div class="card my-2">
      <div class="card-body">
        <h5 class="card-title">{{ new_item.title }}</h5>
        <h6 class="card-subtitle mb-2 text-muted">{{ new_item.date|date:"d.m.Y" }}</h6>
        <p class="card-text">{{ new_item.preview }}</p>
        <a href="#" class="card-link">Подробнее</a>
      </div>
    </div>
    {% endfor %}

    
  </div>

  <div class="col-lg-4">
    <div class="card my-2 sticky-top">
      <div class="card-header">
        Фильтры
      </div>
      <div class="card-body">
        <form action="">
          <div class="input-group mb-3">
            <div class="input-group-prepend">
              <span class="input-group-text" id="basic-addon1">Дата от...</span>
            </div>
            <input type="date" class="form-control" name="dateFrom">
          </div>
          <div class="input-group mb-3">
            <div class="input-group-prepend">
              <span class="input-group-text" id="basic-addon1">Дата до...</span>
            </div>
            <input type="date" class="form-control" name="dateTo">
          </div>

          <button type="submit" class="btn btn-primary btn-block">Фильтровать</button>
        </form>
      </div>
    </div>
  </div>

</div>

<div class="row justify-content-center align-items-center mt-3 mb-n3">
  <nav aria-label="Page navigation example">
    <ul class="pagination">
      <li class="page-item"><a class="page-link" href="#">Previous</a></li>
      <li class="page-item"><a class="page-link" href="#">1</a></li>
      <li class="page-item"><a class="page-link" href="#">2</a></li>
      <li class="page-item"><a class="page-link" href="#">3</a></li>
      <li class="page-item"><a class="page-link" href="#">Next</a></li>
    </ul>
  </nav>
</div>


{% endblock %}